default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: phonebook_development
test:
  <<: *default
  database: phonebook_test

production:
  <<: *default
  database: phonebook_production
  username: phonebook
  password: <%= ENV['PHONEBOOK_DATABASE_PASSWORD'] %>